### ISSUE TITLE
Show error in UI when 500 is returned

### ISSUE THREAD

**Issue by elcojacobs** [BrewBlox/brewblox-ui#1223]
When devcon throws a 500, the only way to see it is to dig into the network tab of the debugger.

We should show the actual error in the UI, not just 500.
Maybe we need to use a different error code for firmware errors, as this is not really a server error in devcon, but a response from firmware.

**Comment by steersbob** [comment]
https://github.com/BrewBlox/brewblox-devcon-spark/blob/develop/brewblox_devcon_spark/exceptions.py defines the non-500 exceptions.

Issue seems related to https://github.com/axios/axios/issues/960
