### ISSUE TITLE
Add the possibility to control a setpoint with a potentiometer

### ISSUE THREAD

**Issue by galax3** [BrewBlox/brewblox-ui#1471]
**Is your feature request related to a problem? Please describe.**
We want to use a physical potentiometer on our brewing desk to control the setpoint of a kettles temperature (target value). Using a touch pad or keyboard is sometimes not possible.

**Describe the solution you'd like**
A possibility to attach an analog value to a setpoint and define temperature ranges.

**Describe alternatives you've considered**
I dont see any real alternative if we want to use physical controls instead of software.

Thank you!

**Comment by steersbob** [comment]
We're currently working on integration of Brewblox and [Node-RED](https://nodered.org/). That seems like the best fit for this use case.

Please drop me a message on the forum, and we can discuss how to hook up your potentiometer.
Closing this issue. It's a valid feature request, but not related to the UI repo.
