### ISSUE TITLE
fetch blocks (mock api) not working from external machine

### ISSUE THREAD

**Issue by elcojacobs** [BrewBlox/brewblox-ui#15]
When opening the blocks page from an external machine, eg opening 192.168.0.112:8080, fetching the blocks fails.

Maybe explained by this:

The request header has:
```
host: localhost:8080
```

Probably should be:
```
host: 192.168.0.112:8080
```

**Comment by Gaya** [comment]
Yeah, the url should adapt to the machine running the app. Good find.

**Comment by elcojacobs** [comment]
host in fetch function to simpley 'api' resolves it (removing ip and port).

**Comment by Gaya** [comment]
@elcojacobs sure, but only in browser AND if the api is located on the same hostname and path as the current visited address.

If you were to make a contained app outside of a browser it wouldn't work (path is something like `/Applications/BrewBlox/storage/<random-string>/bla/some-other-path`.

We should make it a url which is replaced by webpack on build. That way we can make it build environment specific and independent of the shell of the app.

**Comment by Gaya** [comment]
Discussed this issue. We agreed that when the api service can not be reached (inside of an for instance, where the host is unknown) we'll ask the user where the service is located.
We can have this as a setup step before using the app, scanning for nearby brewblocks servers

**Comment by steersbob** [comment]
There are no current plans to support the default services being hosted anywhere other than the same docker-compose environment.

Any future changes to this architecture will only come as part of a larger design, so closing this issue.
