### ISSUE TITLE
Help offer

### ISSUE THREAD

**Issue by pidtuner** [BrewBlox/brewblox-ui#1678]
Hi, I am the developer of [pidtuner.com](https://pidtuner.com).

Sorry I don't know how else to communicate. Just offering my help for PID tuning in your project.

Feel free to write to pidtuner@pidtuner.com as well.

**Comment by steersbob** [comment]
Hi,
Help with smoothly integrating the two systems would be much appreciated.
If it's convenient, this is our discord: https://discord.gg/WaFYD2jaaT.
If not, we can indeed drop you a mail.
