### ISSUE TITLE
Close and Duration box on graph is in the exact wrong place

### ISSUE THREAD

**Issue by MarkMarine** [BrewBlox/brewblox-ui#394]
The "Close" and duration selection box is almost always covering the part of the graph I'm interested in, what's happening right now. This should either be draggable, or just moved over to the bottom right, under the x axis of the graph, not in the display area.

**Comment by steersbob** [comment]
Alternative implementation: add a plotly graph title to full-screen graphs. This would shift the graph downward a bit, leaving room for a close button.
