### ISSUE TITLE
Display widget graph while editing settings

### ISSUE THREAD

**Issue by steersbob** [BrewBlox/brewblox-ui#410]

**Comment by j616** [comment]
Suggestion for a possible design pattern for this. Widgets tend to have two types of windows/popovers that may be opened. One is the configuration popover and one is the graph view. These are both parts of a single widget. It may make sense from a user perspective if they were part of the same window. A user clicks on a button on the widget to get a "detailed view" window. This window could contain tabs that are quick to move between when viewed on smaller devices or a side-by-side view on larger devices. Both tabs and side-by-side will allow users to easily view both the graphs and configurable settings on a PID for example.

**Comment by steersbob** [comment]
It'd require some reshuffling of where elements live in code, but the general idea seems workable.

- mobile: always tabbed
- desktop: default tabbed, choose between tabbed and split-screen view

**Comment by steersbob** [comment]
Graph and SetpointProfile now have a preview graph. We'll tinker with them a bit before deciding on whether we want to implement it for all widgets with graph data.
