### ISSUE TITLE
Indicate when block not driving anything

### ISSUE THREAD

**Issue by j616** [BrewBlox/brewblox-ui#423]
**Is your feature request related to a problem? Please describe.**
I cannot easily tell if a block is not driving anything. This can be when I have both a setpoint and setpoint profile for driving by beer temp and I only use one at a time. Or it could be when setting up a new system and debugging issues.

**Describe the solution you'd like**
Either indicate that the block is not active, as with certain blocks when you disable your setpoint, or some other means of displaying when something is/isn't connected to other blocks.

**Describe alternatives you've considered**
There is no current workaround beyond looking through blocks you may suspect are connected incorrectly. Another alternative solution would be a graph view. Though showing un-connected nodes may still be useful in debugging in this case.

**Comment by steersbob** [comment]
Related to #363
