### ISSUE TITLE
Finished profiles leave setpoint unset

### ISSUE THREAD

**Issue by j616** [BrewBlox/brewblox-ui#425]
**Describe the bug**
When a setpoint profile finishes, it leaves its outputted value unset

**To Reproduce**
1. Create a setpoint profile and populate it
2. Leave it to run to completion

**Expected behavior**
Setpoint holds at final temperature once completed

**Additional context**
The expected behaviour was the default in BrewPi so is unexpected in BrewBlox. A floating setpoint that isn't spotted, particularly after a cold crash, could adversely affect beer.

**Comment by j616** [comment]
Thought on this. I wonder if it'd make sense to turn the setpoint profile into a form of setpoint driver. That way, when it finishes it will just stop "driving" the main setpoint. 

It also means in a setup where you only occasionally use profiles (e.g. mainly fixed temps and ramp down for cold crash once ferm finished) you can disable the profile driver which will clearly display "disabled" rather than having to change which setpoint (profile or regular) is being used by the setpoint pair.

**Comment by steersbob** [comment]
Our initial idea to resolve the issues around SetpointProfile was to merge Setpoint and SetpointProfile. The merged block would have multiple modes: disabled, static, and profile. 

A driver is a valid alternative, but does have the disadvantage of making configurations slightly more complex. 

We'll likely make the final decision on this when we start implementation.
