### ISSUE TITLE
Dialogues not closing after creations

### ISSUE THREAD

**Issue by j616** [BrewBlox/brewblox-ui#460]
**Describe the bug**
Regression. Dialogue boxes for creating dashboards/widgets no longer close after you've created the item.

**To Reproduce**
1. Click on dashboard/widget in wizardry.
2. Follow instructions to completion.
3. Click `create`

**Expected behavior**
I expect the dialogue to close after creating the new dashboard/widget

**Desktop (please complete the following information):**
 - Linux
 - Chrome
 - Version 71.0.3578.98

**Comment by steersbob** [comment]
Fixing this now for the dashboard wizard, but unable to reproduce this for the other wizards.
