### ISSUE TITLE
Setpoint "enabled" now inconsistent with generic enabled

### ISSUE THREAD

**Issue by j616** [BrewBlox/brewblox-ui#466]
A generic method of enabling/disabling blocks (e.g. setpoint drivers) was added. Setpoints have always had an `enabled` switch. This switch is now inconsistent with the UI concept of "enabled/disabled" used elsewhere. Should the setpoints be updated to use the same enable/disable mechanism used elsewhere?

**Comment by steersbob** [comment]
This and #465 seem to be related issues. We'll soon do a pass over all widgets to clean up their layout.

**Comment by steersbob** [comment]
This seems to be rendered irrelevant after recent setpoint changes. Closing issue.
