### ISSUE TITLE
[Session View] Can't select a field when filtering

### ISSUE THREAD

**Issue by glibersat** [BrewBlox/brewblox-ui#524]
When you create a session and want to select the SetpointPair for example (to have both PV and SP), if you filter to search the tree, then you can't select anything. Your pointer will change to a "blocked" sign and then you have to remove your filter and go back searching for yourself in the tree. This makes the filtering feature unusable.

**To Reproduce**
1. Go to a Session View
2. Create a new session
3. In the fields, filter to whatever you have in the list
4. Try to select a SSPair or any other group

**Expected behavior**
You should be able to select a group that contains two fields, as you can do when not filtered.

Using Firefox on linux.

![image](https://user-images.githubusercontent.com/262663/56194029-527bff00-6032-11e9-91cc-4e419b69ed30.png)

**Comment by steersbob** [comment]
The issue seems to be that it won't expand to leaf nodes, and it won't let you select nodes with children.
If you search for "PID", it won't let you select that node. If you search for "active", it will let you select that node inside the PID.

Needless to say, this is not expected behavior.
