### ISSUE TITLE
Unable to select "live" display modes in graph widget

### ISSUE THREAD

**Issue by adempewolff** [BrewBlox/brewblox-ui#539]
**Describe the bug**
I am unable to switch the graph period to live modes (ie. "live: duration to now" or "live: date to now").  Each time after clicking apply, the graph widget appears to refresh, but it has only reverted to "fixed:date-duration" (which can be verified by checking the settings dialogue.

**To Reproduce**
Spark/blewblox are currently controlling a fermentation so I can't try to reproduce from a blank slate but...

1. Look at graph widget created on a classic brewpi arrangement dashboard that has been controlling processes for a couple days.
2. Click on settings button of graph widget.
3. Click on period settings
4. click on display type (currently "Fixed: duration since date")
5. use drop down menu in dialogue to switch to either live mode
6. click apply
7. close settings dialogue
8. reopen settings dialogue
9. note that the period settings display type has reverted to "Fixed: duration since date"

**Expected behavior**
Changing the display type in the settings dialogue will both a) change the actual displayed data and b) result in a persistent change to that settings.

**Actual behavior**
Switching to live modes results in the setting reverting to "fixed: duration since date."  Switching to other fixed modes completely broke the graph widget (no data appears no matter what settings are chosen).

**Browser**
 - OS: Ubuntu 18.04
 - Browser: Chromium Version 73.0.3683.86

**Brewblox server:**
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
Docker version 18.09.0, build 4d60db4
docker-compose version 1.24.0, build 0aa5906
BREWBLOX_PORT_HTTP=None
BREWBLOX_CFG_VERSION=0.2.1
BREWBLOX_RELEASE=edge
BREWBLOX_PORT_HTTPS=None
BREWBLOX_PORT_MDNS=None

**Attachments**
brewblox logs:
https://termbin.com/u05s

browser network activity:
[graph_settings_bug.zip](https://github.com/BrewBlox/brewblox-ui/files/3105018/graph_settings_bug.zip)

**Comment by adempewolff** [comment]
Here's a longer capture of network data where I break the graph by switching to "fixed: date to duration" (so no data appears at all, using the timespan shortcuts to get the data back, and see all sorts of unexpected behavior as I try switching to various display settings.
[graph_settings_bug2.zip](https://github.com/BrewBlox/brewblox-ui/files/3105036/graph_settings_bug2.zip)

**Comment by steersbob** [comment]
Thanks for the report! It's clear what the error is. I'll have a look at why it's happening.
