### ISSUE TITLE
process view part placement offset vertically by 15 units

### ISSUE THREAD

**Issue by adempewolff** [BrewBlox/brewblox-ui#549]
**Describe the bug**
Many--but not all--parts are offset -15 (vertical axis) units from the clicked location.  If you click in the middle of the grid this results in an error (no room to place).  If you click at the top of the grid the part is placed, but at the bottom of the grid.

**To Reproduce**
1. Create a new process view.
2. Click "New"
3. Click on a square in the middle of the grid space.
4. Select a kettle, large kettle, or heating element (probably others as well)
5. Notice placement error.
6. Next click a square at the very top of the grid.
7. select affected part again
8. Notice part is placed 15 units below where you clicked.

**Expected behavior**
Parts will be placed where you initially clicked.

**Browser info:**
 - OS: Ubuntu 18.04
 - Browser: Chromium 73.0.3683.86

**Additional context**
Exported process widget and network activity to create it:
[process_view_part_placement_bug.zip](https://github.com/BrewBlox/brewblox-ui/files/3114219/process_view_part_placement_bug.zip)

**Comment by adempewolff** [comment]
Actually all parts seem to have this problem.  I was thinking I remembered some valves placing correctly a couple days ago, but I may have just not noticed that it didn't place where I clicked.

**Comment by steersbob** [comment]
Edit: never mind, I found the problem =)

For clarification, while I try and replicate this: which units are you referring to? Grid squares?
The grid origin is in the top left corner. You describe parts being placed lower. I assume that means a positive offset (number in top left corner of the grid square is 0,15 if you clicked in 0,0)?
