### ISSUE TITLE
ProcessView Flows

### ISSUE THREAD

**Issue by Gaya** [BrewBlox/brewblox-ui#60]
Implement flows as demonstrated on https://brewpi-ui-demo.herokuapp.com/processview/herms-automated-valves

- [x] Figure out paths from sources
- [x] Handle loops in paths
- [x] Handle conflicting flows
- [x] Flowing from has to be a list of entry points
- [x] Display flowing paths through arrows (tee piece)
- [x] Rewrite flowingFrom / flowingTo to points of flow per part (edge to centre, positive or negative)
- [x] Rethink flowing of arrows by only using `part.flow`
- [x] Solve conflicting flows, pick strongest one
- [x] Valve parts
- [ ] Calculate input outcome from calculated outputs
- [x] Multiple sources
- [ ] Multiple spaces parts
- [ ] Path friction (height diff)
- [x] Parts with power
- [x] Multiple flows through parts
- [x] Display current fluids (water / beer / lava)
- [ ] Pump in loop is an error

**Comment by steersbob** [comment]
Closing this issue, and making separate issues for future work.
