### ISSUE TITLE
Support single-channel DS2408 actuators

### ISSUE THREAD

**Issue by steersbob** [BrewBlox/brewblox-ui#646]

**Comment by x24esru** [comment]
I would love to see this implemented. It's my understanding this is just a UI update and that the firmware already supports this. Thanks!

**Comment by steersbob** [comment]
Blocked by https://github.com/BrewBlox/brewblox-firmware/issues/152

Automatic inference of whether the DS2408 is used as 8-channel digital actuator array, or as 2-channel valve array is too fragile, and requires actuators/valves to be linked.

**Comment by x24esru** [comment]
Was this functionality included in the recent onewire class rewrites?
Thanks

**Comment by steersbob** [comment]
The change is scheduled for the next release, now no unexpected bugs have surfaced in the new OneWire code.
We expect to release sometime this week.
