### ISSUE TITLE
Graphs overflow when block width below 3-4

### ISSUE THREAD

**Issue by adempewolff** [BrewBlox/brewblox-ui#769]
**Describe the bug**
When the temperature profile block is resized to a width smaller than 4 blocks the profile graph will overflow (by about half a block).  The same occurs for the graph widget if it is resized smaller than 3 blocks--but that's less of any issue as a 2 block wide graph isn't very useful.

**To Reproduce**
1. Go to a dashboard with a tempreature profile widget.
2. Use cursor to resize the block width to 3 or fewer blocks.
3. Observe profile graph overflowing to the right.

**Expected behavior**
There seems to be plenty of room for compressing the temperature profile graph into 3 blocks of width without overflowing--for example the more information-dense graph widget does so.  Because the temperature profile doesn't display that much information usually, I would like it to be able to take up less screen space that could be better used by more dense widgets.

**Screenshots**
![Screenshot from 2019-07-15 13-43-13](https://user-images.githubusercontent.com/17548750/61237026-7f11e680-a707-11e9-819f-79ba90569d89.png)
![Screenshot from 2019-07-15 13-43-41](https://user-images.githubusercontent.com/17548750/61237025-7f11e680-a707-11e9-8af0-bf97ddc5c087.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chromium 
 - Version: Version 75.0.3770.90 (Official Build)

**Additional context**
This is not a very high priority issue for me.  I just have been noticing it for months now and wanted to file a bug for documentation purposes if nothing else.

**Comment by steersbob** [comment]
Going by the last screenshot, my guess is that the issue is at least partially caused by the title, not the graph itself.
I'll have a look at it, see how it behaves.

**Comment by adempewolff** [comment]
Your right, a shorter title allows for a narrower widget without the graph overflowing.  Maybe either have resizing clip the title text or don't allow resizing below the width of the text?

**Comment by steersbob** [comment]
According to the toolbar code, names should be truncated and postfixed with an ellipsis in this scenario.
I'll mark it down as a regression.
