### ISSUE TITLE
Units for outputValue in PidDisplay

### ISSUE THREAD

**Issue by adempewolff** [BrewBlox/brewblox-ui#770]
**Is your feature request related to a problem? Please describe.**
The PidDisplay object in the process view display fetches outputValue and displays it in percentage units.  This makes a lot of sense for Pids whose output is fed into pwm blocks.  However, for the beer PID whose output is a temperature offset this doesn't make much sense.

![image](https://user-images.githubusercontent.com/17548750/61262916-17828800-a755-11e9-9df8-f672f63fcb29.png)

lines 47-48 of `src/plugins/builder/parts/PidDisplay.vue`
```
        {{ outputValue | round(0) }}
        <small v-if="!!block">%</small>
```

**Describe the solution you'd like**
The easiest fix would be to remove the percentage sign and just let the user interpret the units as they wish.  Alternately, I guess Pids could be configured to have their output associated with certain units.  Or if vue has access to the control chains it could try to infer the units by looking at the upstream and downstream blocks (ie. use percentage if the downstream block is a PWM, degrees Celsius if it's another PID.

**Comment by steersbob** [comment]
The PID has access to the control chains, but the cost-benefit of going through the chain, determining the correct postfix, and then squeezing in a degC is just not worth it.

Agreed on that the % doesn't make sense when used in combination with a Setpoint Driver, so we'll just drop it.
